complite task_06
js-tasks-ru/vue-20230905_ermak80-pass pull request #13
Opened 2023-10-10 21:25 UTC by urzp

2023-10-10 21:26 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-10-13 20:40 UTC, ShGKme requested changes
Требуется убрать лишний `v-bind="$attrs"` на корневом узле.

В остальном все задачи приняты

2023-10-13 20:40 UTC, ShGKme commented on 06-wrappers/06-UiInputDate/components/UiInputDate.vue
> +<template >
Кажется, это не валидный комментарий для ESLint

2023-10-13 20:40 UTC, ShGKme commented on 06-wrappers/02-UiButton/components/UiButton.vue
> +      return classes
Здесь также можно использовать Vue-шные возможности по добавлению классов по условию, например, объект с классами.

2023-10-13 20:40 UTC, ShGKme commented on 06-wrappers/02-UiButton/components/UiButton.vue
> +      classes.push(this.variant!='button'?'button_' + this.variant:this.variant)
Кажется, варианта `button` нет по условию

2023-10-13 20:40 UTC, ShGKme commented on 06-wrappers/06-UiInputDate/components/UiInputDate.vue
> +   </UiInput>
`v-bind="$attrs"` с `inheritAttrs: false` здесь лишние. Все параметры уже сами наследуются, так как `<UiInput>` - корневой элемент. В итоге это реализует функциональность, которая работает из коробки.

2023-10-13 20:40 UTC, ShGKme commented on 06-wrappers/06-UiInputDate/components/UiInputDate.vue
> +      }
Решение через проксирование модели в этой задачи получается сложнее.

Если вместо проксирования `v-model` передавать `modelValue` и обрабатывать нативное событие `@input`, то можно будет достать `valueAsNumber` из `event.target`, в котором будет сразу числовое значение даты. Его можно не парсить, а сразу передавать дальше.В итоге весь этот код выше заменится одной строкой.

2023-10-16 05:46 UTC, urzp commented
Исправлен коммит v-bind="$attrs" .
Этот пул реквест нужно будет удалять, так как после добавления новых задач 
он непроходит тесты

2023-10-16 20:48 UTC, ShGKme commented
> Этот пул реквест нужно будет удалять, так как после добавления новых задач
> он непроходит тесты

Новый пулл реквест будет таким же, так как это запрос на вливание одной ветки в другую, и это всегда ваш `master` в `master` задачника.

Лучше оставить этот PR для сохранения истории обсуждения в ревью по решённым в нём задачам

2023-10-28 15:15 UTC, closed without merging